//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myForecast.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("myForecast.Localization.LanguageStrings", typeof(LanguageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All weather data used by this application is provided by Weather Underground® API.
        /// </summary>
        internal static string ui_AboutAllWeatherDataProvidedByWu {
            get {
                return ResourceManager.GetString("ui_AboutAllWeatherDataProvidedByWu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application icon by.
        /// </summary>
        internal static string ui_AboutApllicationIconBy {
            get {
                return ResourceManager.GetString("ui_AboutApllicationIconBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        internal static string ui_AboutCaption {
            get {
                return ResourceManager.GetString("ui_AboutCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information regarding the Weather Underground® API, please visit http://www.wunderground.com/weather/api.
        /// </summary>
        internal static string ui_AboutForWuApiInfoVisit {
            get {
                return ResourceManager.GetString("ui_AboutForWuApiInfoVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This product is licensed under the terms of the End User License Agreement..
        /// </summary>
        internal static string ui_AboutLicense {
            get {
                return ResourceManager.GetString("ui_AboutLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by Weather Underground®.
        /// </summary>
        internal static string ui_AboutPoweredByWu {
            get {
                return ResourceManager.GetString("ui_AboutPoweredByWu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation by.
        /// </summary>
        internal static string ui_AboutTranslationBy {
            get {
                return ResourceManager.GetString("ui_AboutTranslationBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather icons by: The Weather Channel, LLC weather.com®.
        /// </summary>
        internal static string ui_AboutWeatherIconsBy {
            get {
                return ResourceManager.GetString("ui_AboutWeatherIconsBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string ui_ButtonAbout {
            get {
                return ResourceManager.GetString("ui_ButtonAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ui_ButtonCancel {
            get {
                return ResourceManager.GetString("ui_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ui_ButtonClose {
            get {
                return ResourceManager.GetString("ui_ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string ui_ButtonDone {
            get {
                return ResourceManager.GetString("ui_ButtonDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to settings.
        /// </summary>
        internal static string ui_ButtonGoToSettings {
            get {
                return ResourceManager.GetString("ui_ButtonGoToSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ui_ButtonSave {
            get {
                return ResourceManager.GetString("ui_ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dew point:.
        /// </summary>
        internal static string ui_CurrentDewPoint {
            get {
                return ResourceManager.GetString("ui_CurrentDewPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feels like:.
        /// </summary>
        internal static string ui_CurrentFeelsLike {
            get {
                return ResourceManager.GetString("ui_CurrentFeelsLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity:.
        /// </summary>
        internal static string ui_CurrentHumidity {
            get {
                return ResourceManager.GetString("ui_CurrentHumidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure:.
        /// </summary>
        internal static string ui_CurrentPressure {
            get {
                return ResourceManager.GetString("ui_CurrentPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uv index:.
        /// </summary>
        internal static string ui_CurrentUvIndex {
            get {
                return ResourceManager.GetString("ui_CurrentUvIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind:.
        /// </summary>
        internal static string ui_CurrentWind {
            get {
                return ResourceManager.GetString("ui_CurrentWind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooops - catastrophic error.\nPlease, check the log file for more details..
        /// </summary>
        internal static string ui_DialogCatastrophicError {
            get {
                return ResourceManager.GetString("ui_DialogCatastrophicError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myForecast - Configuration Settings.
        /// </summary>
        internal static string ui_DialogConfigurationSettingsCaption {
            get {
                return ResourceManager.GetString("ui_DialogConfigurationSettingsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error received from WeatherUnderground.
        /// </summary>
        internal static string ui_DialogErrorReceivedFromWu {
            get {
                return ResourceManager.GetString("ui_DialogErrorReceivedFromWu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while connecting to WeatherUnderground. Please, try again in few minutes..
        /// </summary>
        internal static string ui_DialogErrorWhileConnectingToWu {
            get {
                return ResourceManager.GetString("ui_DialogErrorWhileConnectingToWu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No response received from WeatherUnderground. Please, try again in few minutes..
        /// </summary>
        internal static string ui_DialogNoResponseReceivedFromWu {
            get {
                return ResourceManager.GetString("ui_DialogNoResponseReceivedFromWu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to restart the Windows Media Center Application for start menu changes to take effect..
        /// </summary>
        internal static string ui_DialogStartMenuChangesRestartNeeded {
            get {
                return ResourceManager.GetString("ui_DialogStartMenuChangesRestartNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start menu registry key not found, please reinstall myForecast..
        /// </summary>
        internal static string ui_DialogStartMenuRegistryKeyNotFound {
            get {
                return ResourceManager.GetString("ui_DialogStartMenuRegistryKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myForecast - Weather Data Refresh.
        /// </summary>
        internal static string ui_DialogWeatherDataRefreshCaption {
            get {
                return ResourceManager.GetString("ui_DialogWeatherDataRefreshCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast.
        /// </summary>
        internal static string ui_ForecastCaption {
            get {
                return ResourceManager.GetString("ui_ForecastCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading weather data.
        /// </summary>
        internal static string ui_LoadingWeatherDataMessage {
            get {
                return ResourceManager.GetString("ui_LoadingWeatherDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by.
        /// </summary>
        internal static string ui_PoweredByCaption {
            get {
                return ResourceManager.GetString("ui_PoweredByCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api key.
        /// </summary>
        internal static string ui_SettingsApiKey {
            get {
                return ResourceManager.GetString("ui_SettingsApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App shortcut.
        /// </summary>
        internal static string ui_SettingsAppShortcut {
            get {
                return ResourceManager.GetString("ui_SettingsAppShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock time format.
        /// </summary>
        internal static string ui_SettingsClockTimeFormat {
            get {
                return ResourceManager.GetString("ui_SettingsClockTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string ui_SettingsHours {
            get {
                return ResourceManager.GetString("ui_SettingsHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imperial.
        /// </summary>
        internal static string ui_SettingsImperialUnits {
            get {
                return ResourceManager.GetString("ui_SettingsImperialUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrate into the &quot;Start Menu&quot;.
        /// </summary>
        internal static string ui_SettingsIntegrateIntoTheStartMenu {
            get {
                return ResourceManager.GetString("ui_SettingsIntegrateIntoTheStartMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string ui_SettingsLanguage {
            get {
                return ResourceManager.GetString("ui_SettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location code.
        /// </summary>
        internal static string ui_SettingsLocationCode {
            get {
                return ResourceManager.GetString("ui_SettingsLocationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric.
        /// </summary>
        internal static string ui_SettingsMetricUnits {
            get {
                return ResourceManager.GetString("ui_SettingsMetricUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string ui_SettingsMinutes {
            get {
                return ResourceManager.GetString("ui_SettingsMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh interval.
        /// </summary>
        internal static string ui_SettingsRefreshInterval {
            get {
                return ResourceManager.GetString("ui_SettingsRefreshInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather units.
        /// </summary>
        internal static string ui_SettingsWeatherUnits {
            get {
                return ResourceManager.GetString("ui_SettingsWeatherUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string ui_UvIndex_High {
            get {
                return ResourceManager.GetString("ui_UvIndex_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string ui_UvIndex_Low {
            get {
                return ResourceManager.GetString("ui_UvIndex_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate.
        /// </summary>
        internal static string ui_UvIndex_Moderate {
            get {
                return ResourceManager.GetString("ui_UvIndex_Moderate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very High.
        /// </summary>
        internal static string ui_UvIndex_VeryHigh {
            get {
                return ResourceManager.GetString("ui_UvIndex_VeryHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Low.
        /// </summary>
        internal static string ui_UvIndex_VeryLow {
            get {
                return ResourceManager.GetString("ui_UvIndex_VeryLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weather alert.
        /// </summary>
        internal static string ui_WeatherAlertCaption {
            get {
                return ResourceManager.GetString("ui_WeatherAlertCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire Date.
        /// </summary>
        internal static string ui_WeatherAlertExpireDate {
            get {
                return ResourceManager.GetString("ui_WeatherAlertExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather alert information is not available at the moment.
        /// </summary>
        internal static string ui_WeatherAlertInfoNotAvailable {
            get {
                return ResourceManager.GetString("ui_WeatherAlertInfoNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string ui_WeatherAlertStartDate {
            get {
                return ResourceManager.GetString("ui_WeatherAlertStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Up/Down buttons to scroll.
        /// </summary>
        internal static string ui_WeatherAlertUseUpDownButtonsToScroll {
            get {
                return ResourceManager.GetString("ui_WeatherAlertUseUpDownButtonsToScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weather settings.
        /// </summary>
        internal static string ui_WeatherSettingsCaption {
            get {
                return ResourceManager.GetString("ui_WeatherSettingsCaption", resourceCulture);
            }
        }
    }
}
